server:
  port: 3344

spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:tingxuelouwq/microservice-config.git

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservice-config-server-3344
    prefer-ip-address: true

info:
  app.name: kevin-microservice
  company.name: www.kevinq.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}