server:
  port: 9002

spring:
  application:
    name: microservice-hystrix-turbine

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservice-hystrix-turbine-9002
    prefer-ip-address: true  #访问路径可以显示IP地址

info:
  app.name: kevin-microservice
  company.name: www.kevinq.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

turbine:
  app-config: microservice-dept
  cluster-name-expression: new String("default")
  combine-host-port: true
