server:
  port: 80

spring:
  application:
    name: microservice-feign

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservice-consumer-dept-feign
    prefer-ip-address: true  #访问路径可以显示IP地址

info:
  app.name: kevin-microservice
  company.name: www.kevinq.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

