server:
  port: 9006

spring:
  application:
    name: microservice-config-bus-client
  rabbitmq:
    host: localhost
    port: 5672
    username: kevin
    password: tttx

management:
  endpoints:
    web:
      exposure:
        include: refresh
